version: "3.7"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    # hostname: localhost
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./docker/data:/var/lib/postgresql/data
  client:
    container_name: client
    ports:
     - 3000:3000
    build:
      context: docker/client
      dockerfile: Dockerfile
    volumes:
      - ./docker/client:/usr/src/app/
    env_file:
      - ./docker/client/.env
    user: "${UID}:${GID}"
    restart: always
  api:
    container_name: api
    ports:
      - "5000:5000"
    build:
      context: docker/api
      dockerfile: Dockerfile
    volumes:
      - ./docker/api:/usr/src/app/
    env_file:
      - ./docker/api/.env
    restart: always
volumes:
  postgres: